##################################################################
#  Machine Dependencies - this file is included automatically
#     into the main Makefile
#
# This file contains definitions below for x86 running Linux
# It has *not* been tested!
##################################################################
